/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#111317',
        'surface': '#111317',
        'surface-bright': '#37393d',
        'surface-container-lowest': '#0c0e12',
        'surface-container-low': '#1a1c1f',
        'surface-container': '#1e2023',
        'surface-container-high': '#282a2e',
        'surface-container-highest': '#333539',
        'on-surface': '#e2e2e7',
        'on-surface-variant': '#b9cbbb',
        'inverse-surface': '#e2e2e7',
        'inverse-on-surface': '#2e3034',
        'outline': '#849586',
        'outline-variant': '#3b4b3e',
        'surface-tint': '#00e383',
        'primary': '#f2fff1',
        'on-primary': '#00391d',
        'primary-container': '#00ff94',
        'on-primary-container': '#00713f',
        'inverse-primary': '#006d3c',
        'primary-fixed': '#5bffa1',
        'primary-fixed-dim': '#00e383',
        'on-primary-fixed': '#00210e',
        'on-primary-fixed-variant': '#00522c',
        'secondary': '#c6c6c6',
        'on-secondary': '#303030',
        'secondary-container': '#474747',
        'on-secondary-container': '#b5b5b5',
        'tertiary': '#fefbfd',
        'on-tertiary': '#303032',
        'tertiary-container': '#e1dee1',
        'on-tertiary-container': '#626264',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-1px', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.5px', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '34px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['17px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'label-lg': ['13px', { lineHeight: '18px', letterSpacing: '0.5px', fontWeight: '600' }],
        'label-md': ['11px', { lineHeight: '16px', fontWeight: '500' }],
      },
      borderRadius: {
        'card': '24px',
        'button': '16px',
        'thumbnail': '8px',
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
      },
      backdropBlur: {
        'glass': '20px',
        'glass-heavy': '40px',
      },
    },
  },
  plugins: [],
}
